version: "3.8"

services:
  db:
    image: postgres:15
    container_name: drop-it_postgres
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: on-failure

  s3:
    image: minio/minio:latest
    container_name: drop-it_s3
    env_file:
      - .env
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    restart: unless-stopped

volumes:
  pgdata:
  minio_data:
