version: "3.8"

services:
  db:
    image: postgres:15
    container_name: drop-it_postgres
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: on-failure

volumes:
  pgdata: