from typing import Protocol

from app.models import Drop, Genre
from app.models.user import User


class IUserRepository(Protocol):

    async def get_admin_by_username(self, username: str) -> User | None: ...
    async def get_user_by_id(self, user_id: str) -> User | None: ...
    async def get_user_by_username(self, username: str) -> User | None: ...
    async def get_user_by_email(self, email: str) -> User | None: ...
    async def save_user(self, user: User) -> User: ...


class IDropRepository(Protocol):
    async def save_drop(self, drop: Drop) -> Drop: ...
    async def get_genre_by_id(self, genre_id: str) -> Genre | None: ...
    async def get_drop_by_id(self, drop_id: str) -> Drop | None: ...
    async def count_drops(self, genre_id: str = None, artist_id: str = None) -> int: ...
    async def list_genres(self) -> list[Genre]: ...

    async def list_drops(
        self, page: int, page_size: int, genre_id: str = None, artist_id: str = None
    ) -> list[Drop]: ...
