from typing import Protocol

from app.db.models import Drop
from app.db.models.user import User


class IUserRepository(Protocol):

    async def get_user_by_id(self, user_id: int) -> User | None: ...
    async def get_user_by_username(self, username: str) -> User | None: ...
    async def get_user_by_email(self, email: str) -> User | None: ...
    async def save_user(self, user: User) -> User: ...


class IDropRepository(Protocol):
    async def save_drop(self, drop: Drop) -> Drop: ...
